package javaee.androidclient.rest;


import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 *  Swagger-generation beacon model
 *
 *  @author Swagger.io
 *  @Autogenerated by Swagger
 */
@ApiModel(description = "")
public class Beacon {

    @SerializedName("beaconId")
    private String beaconId = null;
    @SerializedName("longitude")
    private Double longitude = null;
    @SerializedName("latitude")
    private Double latitude = null;
    @SerializedName("height")
    private Double height = null;
    @SerializedName("name")
    private String name = null;
    @SerializedName("room")
    private Integer room = null;

    /**
     * Eindeutiger Identifier des Beacons
     **/
    @ApiModelProperty(value = "Eindeutiger Identifier des Beacons")
    public String getBeaconId() {
        return beaconId;
    }

    public void setBeaconId(String beaconId) {
        this.beaconId = beaconId;
    }

    /**
     * Die Longitude der Beacon-Position
     **/
    @ApiModelProperty(value = "Die Longitude der Beacon-Position")
    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * Die Latitude der Beacon-Position
     **/
    @ApiModelProperty(value = "Die Latitude der Beacon-Position")
    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * Die H�he der Beacon-Position über dem Meeresspiegel
     **/
    @ApiModelProperty(value = "Die H�he der Beacon-Position �ber dem Meeresspiegel")
    public Double getHeight() {
        return height;
    }

    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * Ein Name f�r diesen Beacon, welcher die menschliche Identifikation der Beacons erleichtert
     **/
    @ApiModelProperty(value = "Ein Name f�r diesen Beacon, welcher die menschliche Identifikation der Beacons erleichtert")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Die Nummer des Raumes in dem sich der Beacon befindet
     **/
    @ApiModelProperty(value = "Die Nummer des Raumes in dem sich der Beacon befindet")
    public Integer getRoom() {
        return room;
    }

    public void setRoom(Integer room) {
        this.room = room;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Beacon beacon = (Beacon) o;
        return (beaconId == null ? beacon.beaconId == null : beaconId.equals(beacon.beaconId)) &&
                (longitude == null ? beacon.longitude == null : longitude.equals(beacon.longitude)) &&
                (latitude == null ? beacon.latitude == null : latitude.equals(beacon.latitude)) &&
                (height == null ? beacon.height == null : height.equals(beacon.height)) &&
                (name == null ? beacon.name == null : name.equals(beacon.name)) &&
                (room == null ? beacon.room == null : room.equals(beacon.room));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (beaconId == null ? 0 : beaconId.hashCode());
        result = 31 * result + (longitude == null ? 0 : longitude.hashCode());
        result = 31 * result + (latitude == null ? 0 : latitude.hashCode());
        result = 31 * result + (height == null ? 0 : height.hashCode());
        result = 31 * result + (name == null ? 0 : name.hashCode());
        result = 31 * result + (room == null ? 0 : room.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Beacon {\n");

        sb.append("  beaconId: ").append(beaconId).append("\n");
        sb.append("  longitude: ").append(longitude).append("\n");
        sb.append("  latitude: ").append(latitude).append("\n");
        sb.append("  height: ").append(height).append("\n");
        sb.append("  name: ").append(name).append("\n");
        sb.append("  room: ").append(room).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
